Add vault structure
obsidian-community/obsidian-hub pull request #2
Opened 2021-09-21 20:03 UTC by argenos

2021-09-22 11:17 UTC, kometenstaub requested changes

2021-09-22 11:17 UTC, kometenstaub commented on CONTRIBUTING.md
> +	- The *Default location for new attachments* should be the folder `09.01 - Note attachments`
This needs to be 10.01

2021-09-22 11:17 UTC, kometenstaub commented on CONTRIBUTING.md
> +	![[file-and-link-settings.png]]
The screenshot needs to be updated because of the attachments folder

2021-09-22 11:24 UTC, kometenstaub commented on CONTRIBUTING.md
> +- [[01.01 - Plugins|Community plugins]] - This folder is pre-populated with information from the [obsidian-releases]() repository. Here you can add more information about the plugin itself. For [[09.
[[09.02 - How To|how to]]

2021-09-22 11:24 UTC, kometenstaub commented on 09 - Digital Garden/09.01 - Topics/Begginer guides.md
> +# Begginer guides
Typo; same typo in file name.

2021-09-22 11:28 UTC, kometenstaub requested changes

2021-09-22 11:28 UTC, kometenstaub commented on 02 - Community plugins/02 - Community plugins.md
> +- [[01.01 - Plugins|Community plugins]] - This folder is pre-populated with information from the [obsidian-releases]() repository. Notes in this folder might have missing information (marked with the
[[02.01 - Plugins|Community plugins]]

2021-09-22 11:28 UTC, kometenstaub commented on 02 - Community plugins/02 - Community plugins.md
> +	- Click on [[09.06 - How To]] if you want to add how to do something with a plugin.
[[09.02 - How To]]

2021-09-22 19:39 UTC, argenos commented
@kometenstaub thanks for catching all those broken links! 

@ericaxu we could merge this! I'll add the GitHub guide on a separate commit/PR (it's a much smaller change).

2021-09-23 18:57 UTC, kometenstaub requested changes
I also checked it out locally and took a quick look, apart from changing `alias` to `aliases` I didn't find anything else.
(`alias` is used in 86 notes, `aliases` in 441)

2021-09-23 18:57 UTC, kometenstaub commented on 00 - Meta/00 - Meta.md
> +alias:
I know that `alias` also works, but in the docs we only say to use `aliases`, so we shouldn't confuse contributors.
https://help.obsidian.md/How+to/Add+aliases+to+note#Set+aliases

2021-09-23 19:21 UTC, kometenstaub requested changes
I think you didn't search and replace `alias:` with `aliases:` but rather `alias` with `aliases` which resulted in a lot of false positives. I suggest to hard-reset to the commit before.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/02.01 - Plugins.md
> +- [[02 - Community plugins/02.01 - Plugins/obsidian-command-aliases-plugin|obsidian-command-aliases-plugin]]
That was unintended.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/dangerzone-writing-plugin.md
> +![GitHub all releases](https://img.shields.io/github/downloads/akaaliases/dangerzone-writing-plugin/total?color=573E7A&logo=github&style=for-the-badge)
These four were unintended.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/dangerzone-writing-plugin.md
> +Repository: [GitHub](https://github.com/akaaliases/dangerzone-writing-plugin)
This one as well.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/extract-highlights-plugin.md
> +![GitHub all releases](https://img.shields.io/github/downloads/akaaliases/extract-highlights-plugin/total?color=573E7A&logo=github&style=for-the-badge)
Four.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/extract-highlights-plugin.md
> +Repository: [GitHub](https://github.com/akaaliases/extract-highlights-plugin)
One.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/obsidian-command-alias-plugin.md
> +![GitHub all releases](https://img.shields.io/github/downloads/yajamon/obsidian-command-aliases-plugin/total?color=573E7A&logo=github&style=for-the-badge)
Four.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/obsidian-command-alias-plugin.md
> +# Command aliases
Next three from here.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/obsidian-extract-pdf-highlights.md
> +![GitHub all releases](https://img.shields.io/github/downloads/akaaliases/obsidian-extract-pdf-highlights/total?color=573E7A&logo=github&style=for-the-badge)
Four.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/obsidian-extract-pdf-highlights.md
> +Repository: [GitHub](https://github.com/akaaliases/obsidian-extract-pdf-highlights)
Also here.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/obsidian-footnotes.md
> +![GitHub all releases](https://img.shields.io/github/downloads/akaaliases/obsidian-footnotes/total?color=573E7A&logo=github&style=for-the-badge)
Four.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/obsidian-footnotes.md
> +Repository: [GitHub](https://github.com/akaaliases/obsidian-footnotes)
One.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/obsidian-journey-plugin.md
> +![GitHub all releases](https://img.shields.io/github/downloads/akaaliases/obsidian-journey-plugin/total?color=573E7A&logo=github&style=for-the-badge)
Four.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/obsidian-journey-plugin.md
> +Repository: [GitHub](https://github.com/akaaliases/obsidian-journey-plugin)
One.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/pdf-to-markdown-plugin.md
> +![GitHub all releases](https://img.shields.io/github/downloads/akaaliases/obsidian-extract-pdf/total?color=573E7A&logo=github&style=for-the-badge)
Four.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.01 - Plugins/pdf-to-markdown-plugin.md
>  Mobile compatible: [[Mobile-compatible plugins|Yes]]
One.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.02 - Categories/02.02 - Categories.md
> +3. Add a link to the plugin in question using its aliases, e.g. `[[obsidian-dataview|Dataview]]`
This one as well.

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.02 - Categories/Automation.md
> +aliaseses:
Why did it change `aliases` to `aliaseses`?

2021-09-23 19:21 UTC, kometenstaub commented on 02 - Community plugins/02.02 - Categories/Shortcut.md
> +- [[obsidian-command-aliases-plugin|Command aliases]]
One.

2021-09-23 19:34 UTC, kometenstaub approved these changes
I didn't find any false positives. :+1:

2021-09-23 19:36 UTC, merged