Create Volunteer Doc Writers
obsidian-community/obsidian-hub pull request #273
Opened 2022-01-30 12:58 UTC by AB1908

## Edited

## Added

## Checklist
- [ ] before creating a new note, I searched the vault
- [ ] new notes have the `.md` extension
- [ ] (if applicable) attached images have descriptive file names
- [ ] (if applicable) for new notes in the folder "04 - Guides, Workflows, & Courses", I added a link to them in one of the "for {group X}" overviews: https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses

2022-01-30 15:17 UTC, claremacrae commented
A note to reviewers:
- I wonder whether the title "Volunteer **Plugin** Doc Writers" might be clearer?
- I don't know if it matters that there's no metadata at the top of the file...

2022-01-30 15:19 UTC, claremacrae requested changes
The checks have pointed out that there is no .md file extension on this file...

If you know how, please could you rename it to fix that?

Many thanks

2022-01-30 16:38 UTC, AB1908 commented
I dunno how I missed something like that. I made a few of the changes but have left if with no metadata.

2022-02-11 18:58 UTC, argenos approved these changes

2022-02-11 18:59 UTC, argenos commented
@claremacrae I believe you need to approve since you requested changes last time

2022-02-13 22:31 UTC, claremacrae approved these changes
@argenos I'll approve this, because I cannot see how to now apply the suggested edit that I made previously, which was to fix a typo:
You can reach **out** the the plugin developer
->
You can reach out to the plugin developer

2022-02-13 23:24 UTC, claremacrae commented
Thanks for fixing the file extension! :-)

2022-02-14 08:28 UTC, AB1908 commented on 06 - Inbox/Volunteer Plugin Doc Writers.md
> +We'll maintain a list of plugins that need better docs. You can reach out the the plugin developer and collaborate with them to help out. You don't necessarily need technical skills to contribute; yo
Oh my. These mistakes keep slipping through. I'm so sorry ahaha.

2022-02-14 09:54 UTC, merged

2022-02-14 09:55 UTC, claremacrae commented
Merged - thank you very much @AB1908