Removed embed containing broken link
obsidian-community/obsidian-hub pull request #451
Opened 2022-06-04 16:30 UTC by kzhovn

## Edited
This was a link to a roundup line linking Reggie's guide to CSS, which was broken. Reggie's publish site seems to be down, or at least I couldn't find it anywhere, so I removed the link.

## Checklist
- [ ] before creating a new note, I searched the vault
- [ ] new notes have the `.md` extension
- [ ] (if applicable) attached images have descriptive file names
- [ ] (if applicable) for new notes in the folder "04 - Guides, Workflows, & Courses", I added a link to them in one of the "for {group X}" overviews: https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses

2022-06-04 16:44 UTC, lguenth commented
Thank you for noticing! I did a quick search over on Discord and the Web Archive but unfortunately, I couldn't find an alternative. 
Could you please remove the left-over block ID (`^594d70`) in the Roundup note as well?

2022-06-05 15:53 UTC, lguenth requested changes
Could you please remove the left-over block ID (^594d70) in the Roundup note as well?

2022-06-05 20:24 UTC, kzhovn commented
Done.

2022-06-06 10:53 UTC, lguenth approved these changes

2022-06-06 10:53 UTC, merged