Add basic Obsidian ecosystem analysis
obsidian-community/obsidian-hub pull request #496
Opened 2022-09-12 19:36 UTC by Fevol

Edit in browser

2022-09-13 13:29 UTC, lguenth requested changes
Hiya Fevol,
This is fantastic, thank you so much for compiling the data and sharing it with us! There are some minor corrections I would like you to make but overall, I'm happy with how you structured the note. The direct links to your repo are great, if you want to update them, the change will be immediately reflected here.
Apart from that, if you also want to add your translation plugin in a new PR, let us know on Discord and we'll find a way to integrate it without the script we usually run.

Awesome, thanks again!

2022-09-13 13:29 UTC, lguenth commented on 04 - Guides, Workflows, & Courses/Guides/Obsidian ecosystem statistics.md
> +This chart graphs the downloads of community themes on the y-axis,  and the relative age of a theme on the x-axis (from oldest theme to newest theme)
Typo: Extra space between comma and `and the relative`

2022-09-13 13:57 UTC, Fevol commented on 01 - Community/People/Fevol.md
> +- [[obsidian-translate|Obsidian Translate]]
Ah oops! That was indeed a mistake! I'll be releasing it to the store soon enough (hopefully), I've removed it from the author note now. I didn't realize that plugins get linked automatically.

2022-09-14 21:19 UTC, lguenth approved these changes
Awesome, thanks so much for contributing and making the changes! :orange_heart: Approved :partying_face:

2022-09-14 21:20 UTC, lguenth commented
Uh oh. Unless the markdown linter sees a problem I'm currently to blind to find. Sorry, I need to get some sleep before forcing a re-run. :woozy_face:

2022-09-14 21:28 UTC, Fevol commented
Oooh, the linter doesn't like the fact that I've added spaces before the blockquote to separate the data a bit, I'll remove them for now!

2022-09-14 21:30 UTC, Fevol commented
That should fix it hopefully!

2022-09-14 21:38 UTC, lguenth commented
Noice! That was it!

2022-09-14 21:38 UTC, merged